import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`dark ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <div className="z-0 w-screen grid grid-rows-2 absolute">
          <div className="w-full h-full overflow-clip">
            <div className="stripe"></div>
          </div>

          <div className="w-full">
            <div className="Mask w-full h-[200%] absolute overflow-hidden ">
              <div className="stripe-inv"></div>
            </div>
          </div>
        </div>
      
          <SessionProvider>{children}</SessionProvider>
      
      </body>
    </html>
  );
}
